### ISSUE TITLE
"Record conversation" checkbox doesn't appear to do anything

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-server#140]
I know it does what it says (save the conversation log on disk), but given that saving on disk is not accessible in most cases (it's inside the docker or Home Assistant add-on storage) it's not very useful.
The save button seems to be present regardless of whether recording is active or not. The save button is enough to download the log and save it locally.
Perhaps we should remove the "record conversation" checkbox and always show the "save" button?

@rayslxu

**Comment by rayslxu** [comment]
The save button is shown if either (1) it's recording or (2) there is a log of the current conversation. And a log is saved if (1) "save" button is clicked (2) the recording is stopped. 
As a result, once recording is started, then the save button is always there...

Yeah, the logic is kinda confusing...

If we remove the "record conversation" checkbox, then it will keep accumulating logs forever. we will need a page to manage the logs

**Comment by gcampax** [comment]
Are you worried that the logs will be big? I don't think so? This is almond-server, it's a single user on usually a decently sized machine. And we can easily rotate the logs say once a month.
