### ISSUE TITLE
PulseAudio-based echo cancellation is not available in Home Assistant

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-server#160]
The version of PulseAudio built into Home Assistant does not include the echo cancellation modules, so our echo cancellation request is ignored.

**Comment by ad31c0** [comment]
The module (in terms of .so) is there but is not loaded by the hassio_audio PulseAudio server.
It can be loaded by using pactl load-module module-echo-cancel, also from the addon container.

Unfortunately seems it doesn't support aec_method=webrtc for the better algo.

**Comment by gcampax** [comment]
In normal circumstances, at startup PulseAudio loads and keeps loaded `module-filter-heuristics`. This module notices pairs of streams with the `filter.want` property belonging to the same client, sets the `filter.apply` property if meaningful (ie, if the streams actually go out of the same device), and loads `module-filter-apply`. This other module sees the `filter.apply`, loads `module-echo-cancel`, which creates software sources and sinks (indicated with "(echo cancelled)" in the name) and redirects the streams to the echo-cancelled sinks/sources.
If all modules are available, all we need to do is ensure that `module-filter-heuristics` is loaded and we'll get some amount of echo-cancellation. Even a poor algorithm is better than nothing, and later we can ask the Home Assistant people to include webrtc in the OS.

**Comment by gcampax** [comment]
There is also this: https://github.com/stanford-oval/genie-toolkit/issues/294
Although I don't remember what Pi (3 or 4) that occurred on.
