### ISSUE TITLE
"Running Almond Server" steps need more information

### ISSUE THREAD

**Issue by Trial-In-Error** [stanford-oval/almond-server#212]
Hey!

I puzzled my way through "Running Almond Server" in the `README.md` but it would be nice if that section:

- [Linked to podman's installation instructions](https://podman.io/getting-started/installation)
- [Included the snippets for starting/stopping named containers](https://wiki.almond.stanford.edu/user-guide/almond-server)
- Described how to add `docker.io` as a registry in `/etc/containers/registries.conf` so podman can resolve the short-name correctly

**Comment by gcampax** [comment]
Sure. Would you care to send a PR with your proposed changes?
BTW, I'm not sure adding docker.io to registries.conf is necessary. At least, it was not necessary for me. We can put the full name of the image in the instruction to avoid that step if it is necessary.

**Comment by Trial-In-Error** [comment]
Sure! I'd be happy to put together a PR.

As for `registries.conf`, my fresh install of podman v3.0.1 came with a `registries.conf` that had this (commented out):
```
# unqualified-search-registries = ["https://example.com"]
```

So any attempt to install with a short-name resulted in:
```
Error: error getting default registries to try: short-name "stanfordoval/almond-server:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```

**Comment by gcampax** [comment]
What distro are you on? On Fedora, I have:
```
unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "docker.io", "quay.io"]
```
by default.
I suppose if none are configured by default it won't work.

**Comment by Trial-In-Error** [comment]
Odd. I'm on Ubuntu.
