### ISSUE TITLE
Running on Raspberry PI results in "Exec format error"

### ISSUE THREAD

**Issue by julianpoy** [stanford-oval/almond-server#216]
Running on Raspberry PI (Ubuntu 20.04.2) with the Podman command from the README results in

```
{"msg":"exec container process `/usr/bin/npm`: Exec format error","level":"error","time":"2021-06-07T00:29:23.000360758Z"}
```

**Comment by gcampax** [comment]
We only provide builds for x86_64 at the moment. If you would like to run on arm or arm64, you will need to rebuild the container using the Dockerfile in this repository.

**Comment by julianpoy** [comment]
Thank you - worked. Now trying to get it to recognize audio input, but past building & running. Thanks!
