### ISSUE TITLE
Why are you using podman?

### ISSUE THREAD

**Issue by MikeyBeez** [stanford-oval/almond-server#236]
I'm having trouble installing podman on Pop!_OS 21.04.  Is it possible to run this using docker?  Apt-get doesn't find podman.  Snap edge says podman is unstable.  Is there a compelling reason for using this particular "nonstandard" container?

**Comment by gcampax** [comment]
podman allows you to run the container as non-root. This is necessary to access pulseaudio. You can use docker if you don't care about audio support.

(Note that podman is standard in Fedora/RHEL)
