### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by MikeyBeez** [stanford-oval/almond-server#237]
Where is your training data?  Are you just using Mycroft and Snowboy?  Why?

**Comment by MikeyBeez** [comment]
Is you model on Huggingface?

**Comment by gcampax** [comment]
Hi! Let me answer your questions point by point:

The main training data (semantic parsing aka text to meaning) is synthesized using the [genie-toolkit](https://github.com/stanford-oval/genie-toolkit). You can find instructions on [how to generate data and train a model](https://github.com/stanford-oval/thingpedia-common-devices/blob/master/doc/training.md) in the [thingpedia-common-devices repository](https://github.com/stanford-oval/thingpedia-common-devices). I recommend you read our [Genie paper](https://oval.cs.stanford.edu/papers/genie-pldi19.pdf) first though, as that explains how we synthesize data and build a semantic parser. More recent papers ([Schema2QA](https://oval.cs.stanford.edu/papers/schema2qa-cikm2020.pdf), [SKIM](https://arxiv.org/abs/2009.07968)) also expand on the concept for question answering and dialogues.

Snowboy is only used for wake-word detection. We do not use any data or code from Mycroft at the model.

Our model is not on Huggingface at the moment. You can download it from our [releases page](https://wiki.almond.stanford.edu/releases).

**Comment by MikeyBeez** [comment]
Thank you for you interesting replies.  I'm on Pop!_OS 21.04 and Podman steps on Docker.  I was able to build from source, but I backed out using Timeshift because the build is flawed for Debian based distributions.  I suppose I can create a Fedora virtual machine and do the install.  Maybe I'll do that.  I'm glad you aren't using MyCroft.  Somewhere I saw Mycroft.  I think in one of your code files.  It's probably just left over from an old version.  I'll read your paper and reexamine your project.  It looks interesting.  Cheers.

**Comment by gcampax** [comment]
Yes, we have a different backend for the wake-word that uses mycroft instead of Snowboy. That backend is not currently used because there is no high-quality wake-word model we can use.

**Comment by MikeyBeez** [comment]
I use vosk.  It works very well.  Have you tried it?  Here's my virtual assistant repo on Github.  I haven't worked on it lately because I've been researching tech.  I've been thinking about making an intent model, but if I understand what you've done, it seems like a better idea.  I've also been looking for a model that translates from English to Sparql.  Sparql is powerful, but it's a pain, and a transformer seems perfect for that sort of sequence to sequence task.    https://github.com/MikeyBeez/Julie-Julie

**Comment by MikeyBeez** [comment]
https://www.youtube.com/watch?v=Kky-mdzYLq4&t=489s

**Comment by nrser** [comment]
Hope you've had your questions answered, please check out our [forum](https://community.almond.stanford.edu) if you'd like to continue the discussion.
