### ISSUE TITLE
Certificate has expired.

### ISSUE THREAD

**Issue by Johnnii360** [stanford-oval/almond-server#343]
Hi guys!

I hope you finally read this and fix this issue. Since a couple of days your certificate has expired. Some users report that issue and get the message from Genie. Your online version doesn't work either - same issue.

```
Received assistant command time
Error processing queue item UserInput {
  command: { type: 'command', utterance: 'time', platformData: {} }
}
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'CERT_HAS_EXPIRED'
}
Genie says: Sorry, I had an error processing your command: certificate has expired.
```

https://github.com/home-assistant/addons/issues/2519

**Comment by razerbeans** [comment]
My guess would be the following domain is the offender from what I can gather here https://github.com/stanford-oval/genie-server/blob/0c63b723100ad9f875beea1926d1eb22f654fff6/src/config.ts#L92
https://nlp.almond.stanford.edu

**Comment by gcampax** [comment]
Thank you for reporting this. It appears that automatic renewal of the certificate had failed. I updated the certificate and the endpoint is now reachable over TLS with a valid certificate.
