### ISSUE TITLE
I created a YouTube video tutorial about Almond and Home Assistant

### ISSUE THREAD

**Issue by peyanski** [stanford-oval/almond-server#38]
Hello, 
I just published a YouTube tutorial about it and Home Assistant.

This is my video - https://youtu.be/vmNp2RTGY6Q

If you think that the video is helpful you can put the link somewhere.

Either way, keep up the great work :)

**Comment by gcampax** [comment]
Thank you again for the video, I'm closing this issue as there is nothing left to do.
