### ISSUE TITLE
Unhandled Home Assistant entity

### ISSUE THREAD

**Issue by grewhit25** [stanford-oval/almond-server#39]
Almond Server v1.7.2 - Locally hosted.
Home Assistant 0.103.3

I am seeing a continuous stream of Unhandled entities in the almond log.
Does this point to a problem with my configuration or is there a way to filter Unhandled entities.
I cannot find any reference to this kind of report in the documentation.

Here is a very small log sample.

```log
Unhandled Home Assistant entity sensor.xxxxxxxx with domain sensor
Unhandled Home Assistant entity binary_sensor.xxxxxxxx with domain binary_sensor
Unhandled Home Assistant entity group.xxxxxxxx with domain group
```

**Comment by grewhit25** [comment]
Any suggestion on how to filter out these reports? Or even a starting point on investigating them? 

I am assuming these are just entities that are not yet recognised by almond, but they are outputting constantly in the logs.

**Comment by gcampax** [comment]
Thanks for the bug report, yeah this is just a spammy debugging log about unsupported features, and there is no problem for your configuration. I opened a PR to make it quieter.
(OTOH, if you would like to have Almond support those entities, we have a guide at https://almond.stanford.edu/doc/home-assistant-integration.md - we'd love some help!)

**Comment by grewhit25** [comment]
Thanks for the PR and I will definitely be taking a look at the link.

**Comment by grewhit25** [comment]
Your PR appear to have solved the issue. Closing.
