### ISSUE TITLE
ARM64 docker image?

### ISSUE THREAD

**Issue by minnixtx** [stanford-oval/almond-server#50]
I used the instructions to pull and run almond-server with podman, and it wouldn't start because of architecture related error. Is there a docker image for AArch64 architecture? Or is there a configuration change I can make somewhere? This is for an orange pi zero plus2 with an allwinner H5 64bit cpu.

**Comment by gcampax** [comment]
Hi! Thanks for your report! We don't have multiarch images at the moment, primarily because we don't have an arm64 machine to build on. You might be able to install Almond from source though, following the instructions in the README under "Development Setup".
