### ISSUE TITLE
Websocket constantly disconnects

### ISSUE THREAD

**Issue by prologic** [stanford-oval/almond-server#61]
I'm running ALmondServer bahind Traefik as a L7 load labancer and which also provides TLS termiantion with Let's Encrypt certs

The Web UI works just fine.

The conversation.js web socket constantly disconnects. I can't figure out why.

Can anyone help? :)

**Comment by prologic** [comment]
This is my `docker-compose.yml` (_effectively, I run this in a Swarm cluster_):

```#!yaml
---
version: "3.8"

services:
  almond:
    image: stanfordoval/almond-server:latest-portable
    networks:
      - traefik
    volumes:
      - almond:/var/lib/almond-server
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=almond"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:almond.mydomain.com"
      placement:
        constraints:
          - "node.hostname == dm2"
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  traefik:
    external: true

volumes:
  almond:
    driver: local
```

**Comment by grewhit25** [comment]
Almond is expecting connections from the local host 'origin http://127.0.0.1:3000' with a connection upgrade.
So you could try connecting almond-server to your host network, or
alternatively; checkout issue #37 for a proposed workaround using nginx like a sidecar helper, where nginx sets the origin header tricking almond into thinking that the connection is local and also deals with the necessary connection upgrade.

The workaround works for me under docker swarm.

**Comment by prologic** [comment]
Can I ask, Why does this restriction exist if you have to be authenticated in the first place? What can't it accept an Origin of the server's configured FQDN?

**Comment by prologic** [comment]
So another thing, a) That issue is far too long for me to read properly but b) At first glance gleeming over several of the first few comments... c) I'm not actually experiencing any server-side exceptions being thrown or anything likehtat.

In fact, I actually have Home-Asistant + Almond working nicely already.

I have Home-Assitant configured like this:

```#!yaml
almond:
  type: local
  host: https://almond.mydomain.com
```

So it works just fine and I am able to use the Microphone in the Web UI of Home-Assistant or the iOS App (_altuogh the experience here isn't that great because you have to click a few too many times_) just fine!

What I "don't get" is this WebSocket connection problem on the Almond Web UI -- So that particular feature of Almond doesn't work "Start Conversation" from the Web UI -- What is it even for if HA<->Almond is already working as I expect?

**Comment by prologic** [comment]
Man I must be tired :/ I actually feel really silly now. I had enabled the builtin `conversation:` integration in HA and so _that_ was what was being used -- Not Almond at all! In fact I don't even know how Almond works now since I also tried the hosted version with no success (_as in it didn't work at all_)
