### ISSUE TITLE
cvc4 failure on yarn / sqlite3 failure on make

### ISSUE THREAD

**Issue by RMKD** [stanford-oval/almond-server#7]
git cloned, ran `make`

Could you document some more build instructions?

```
19615 verbose stack Error: sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
19615 verbose stack Exit status 1
19615 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
19615 verbose stack     at emitTwo (events.js:126:13)
19615 verbose stack     at EventEmitter.emit (events.js:214:7)
19615 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
19615 verbose stack     at emitTwo (events.js:126:13)
19615 verbose stack     at ChildProcess.emit (events.js:214:7)
19615 verbose stack     at maybeClose (internal/child_process.js:925:16)
19615 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19616 verbose pkgid sqlite3@3.1.13
19617 verbose cwd <path-to-repo>/almond-server
19618 verbose Linux 4.17.5-1-MANJARO
19619 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "sqlite3" "--build-from-source" "--sqlite_libname=sqlcipher" "--sqlite=/usr/"
19620 verbose node v8.11.3
19621 verbose npm  v6.2.0
19622 error code ELIFECYCLE
19623 error errno 1
19624 error sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
19624 error Exit status 1
19625 error Failed at the sqlite3@3.1.13 install script.
19625 error This is probably not a problem with npm. There is likely additional logging output above.
19626 verbose exit [ 1, true ]

```

**Comment by gcampax** [comment]
Hello, and thanks for your interest.
I apologize for the build instructions being out of date. The correct way to build this package is to use [yarn](https://yarnpkg.com). The command is just `yarn`.

**Comment by RMKD** [comment]
Thanks for the response - running `yarn` produces an error related to a `cvc4` header file. Do you know what package depends on it?

node: `v10.7.0`
yarn: `1.7.0`

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '$PROJECTS/almond-server/node_modules/cvc4/build'
  CXX(target) Release/obj.target/cvc4/src/node-cvc4.o
../src/node-cvc4.cpp:12:10: fatal error: cvc4/cvc4.h: No such file or directory
 #include <cvc4/cvc4.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [cvc4.target.mk:101: Release/obj.target/cvc4/src/node-cvc4.o] Error 1
```

**Comment by gcampax** [comment]
You must install the cvc4 library and development headers; these are provided by package cvc4-devel on Fedora, and libcvc4-dev on Ubuntu (Bionic or newer).

You must also install pulseaudio development headers (pulseaudio-libs-devel, or libpulse-dev), and mimic (https://github.com/MycroftAI/mimic)

By the way, this particular port of Almond is not yet stable, or recommended for general use if you're not comfortable with nodejs development. The documentation is in the process of being updated, for the next release of the software (not public yet), which is also have several bug fixes. We will have better build and usage instructions soon.

**Comment by gcampax** [comment]
Closing as we added new build documentation, and also we have official docker builds now, which should allieviate this problem.
